#****************************************************
# Pontificia Universidad Javeriana
# Autor: Juan Diego Ariza
# Profesor: J. Corredor
# Materia: Sistemas Operativos
# Fecha: 13/11/2025
# Fichero: Automatización de Compilación - Sistema de Ficheros
#****************************************************

GCC = gcc
FLAGS = -Wall
PROGRAMAS = LAB_Ficheros01 LAB_Ficheros02 LAB_Ficheros03

all: $(PROGRAMAS)

LAB_Ficheros01:
	$(GCC) $@.c -o $@ $(FLAGS)

LAB_Ficheros02:
	$(GCC) $@.c -o $@ $(FLAGS)

LAB_Ficheros03:
	$(GCC) $@.c -o $@ $(FLAGS)

clean:
	$(RM) $(PROGRAMAS)
