# ****************************************************
# * Nombre: Juan Diego Ariza López
# * Materia: Sistemas Operativos
# * Profesor: J. Corredor
# * Universidad: Pontificia Universidad Javeriana 
# * Fecha: 16/10/2025
# * Descripción: Compilación del cliente y servidor FIFO.
# ****************************************************

GCC = gcc
MODULO =
PROGRAMAS = cliente servidor

cliente:
        $(GCC) $@.c -o $@

servidor:
        $(GCC) $@.c -o $@

all: $(PROGRAMAS)

clean:
        rm -f $(PROGRAMAS)
