GCC = gc

PROGRAMAS = lab01_Ariza lab02_Ariza lab03_Ariza

lab01_Ariza:
        $(GCC)@.c -o $@
lab02_Ariza:
        $(GCC)@.c -o $@
lab03_Ariza:
        $(GCC)@.c -o $@

clean:
        $(RM) $(PROGRAMAS)
