# **************************************************************
# * Nombre: Juan Diego Ariza
# * Materia: Sistemas Operativos
# * Profesor: John Corredor, Ph.D.
# * Universidad: Pontificia Universidad Javeriana
# * Fecha: 30/10/2025
# * Descripción: Compilación de challenges de sincronización
# *************************************************************

GCC = gcc -pthread

PROGS = Challenge01 Challenge02 Challenge03 Challenge04 Challenge05 Challenge06 Challenge07 Challenge08

Challenge01:
	$(GCC) $@.c -o $@

Challenge02:
	$(GCC) $@.c -o $@

Challenge03:
	$(GCC) $@.c -o $@

Challenge04:
	$(GCC) $@.c -o $@

Challenge05:
	$(GCC) $@.c -o $@

Challenge06:
	$(GCC) $@.c -o $@

Challenge07:
	$(GCC) $@.c -o $@

Challenge08:
	$(GCC) $@.c -o $@

all: $(PROGS)

clean:
	rm -f $(PROGS)
