#****************************************************
# Pontificia Universidad Javeriana
# Autor: Juan Diego Ariza
# Prodesor: J. Corredor
# Materia: Sistemas Operativos
# Fichero: Automatización de Compilación
#****************************************************

GCC = gcc
FLAGS = -lm -fopenmp

PROGRAMAS = LAB_OMP01 LAB_OMP02 LAB_OMP03 LAB_OMP04 LAB_OMP05 LAB_OMP06

LAB_OMP01:
	$(GCC) $@.c -o $@ $(FLAGS)

LAB_OMP02:
	$(GCC) $@.c -o $@ $(FLAGS)

LAB_OMP03:
	$(GCC) $@.c -o $@ $(FLAGS)

LAB_OMP04:
	$(GCC) $@.c -o $@ $(FLAGS)

LAB_OMP05:
	$(GCC) $@.c -o $@ $(FLAGS)

LAB_OMP06:
	$(GCC) $@.c -o $@ $(FLAGS)

clean:
	$(RM) $(PROGRAMAS)
